dist: bionic
language: node_js
node_js:
  - '17'

before_script:
  - npm install --location=global @angular/cli
  - npm install --location=global angular-cli-ghpages
  - npm install
  - ng build --aot --base-href="https://warriorsoforlandia.com"

script: npx angular-cli-ghpages -d dist/warriors-site --repo=https://GH_TOKEN@github.com/iamdavidfrancis/warriorsoforlandia.com.git --name="Travis CI" --email=iamdavidfrancis@gmail.com
